project:
  type: website
  output-dir: docs

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3A"
          href: "Hands-on_Ex/Hands-on_Ex03A/Hands-on_Ex03A.html"
        - text: "Hands-on Exercise 3B"
          href: "Hands-on_Ex/Hands-on_Ex03B/Hands-on_Ex03B.html"
        - text: "Hands-on Exercise 4A"
          href: "Hands-on_Ex/Hands-on_Ex04A/Hands-on_Ex04A.html"
        - text: "Hands-on Exercise 4B"
          href: "Hands-on_Ex/Hands-on_Ex04B/Hands-on_Ex04B.html"
        - text: "Hands-on Exercise 4C"
          href: "Hands-on_Ex/Hands-on_Ex04C/Hands-on_Ex04C.html"
        - text: "Hands-on Exercise 4D"
          href: "Hands-on_Ex/Hands-on_Ex04D/Hands-on_Ex04D.html"
        - text: "Hands-on Exercise 5A"
          href: "Hands-on_Ex/Hands-on_Ex05A/Hands-on_Ex05A.html"
        - text: "Hands-on Exercise 5B"
          href: "Hands-on_Ex/Hands-on_Ex05B/Hands-on_Ex05B.html"
        - text: "Hands-on Exercise 5C"
          href: "Hands-on_Ex/Hands-on_Ex05C/Hands-on_Ex05C.html"
        - text: "Hands-on Exercise 5D"
          href: "Hands-on_Ex/Hands-on_Ex05D/Hands-on_Ex05D.html"
        - text: "Hands-on Exercise 5E"
          href: "Hands-on_Ex/Hands-on_Ex05E/Hands-on_Ex05E.html"
        - text: "Hands-on Exercise 6A"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06A.html"
        - text: "Hands-on Exercise 6B"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06B.html"
        - text: "Hands-on Exercise 7"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
        - text: "Hands-on Exercise 8A"
          href: "Hands-on_Ex/Hands-on_Ex08A/Hands-on_Ex08A.html"
        - text: "Hands-on Exercise 8B"
          href: "Hands-on_Ex/Hands-on_Ex08B/Hands-on_Ex08B.html"
        - text: "Hands-on Exercise 8C"
          href: "Hands-on_Ex/Hands-on_Ex08C/Hands-on_Ex08C.html"
        - text: "Hands-on Exercise 9"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
          
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 1 Executive Summary"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01_slides.html" 
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html" 
        - text: "Take-home Exercise 3"
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
        - text: "In-class Exercise 2"
          href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"

    right:
      - href: index.qmd
        text: "Home"
      - about.qmd


format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual
