{
  "hash": "98b0d91f3c39c46655e4986243fb278e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 01\"\nauthor: \"Ang Ming Kwan\"\ndate: \"May 8, 2026\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n## Visual Analytics for Data Discovery: Exploring a Motor Vehicle Insurance Portfolio\n\n## 1 Introduction\n\n### 1.1 Background\n\nInsurers often carry underperforming portfolios where the root causes of poor profitability and high volatility remain unknown. Traditionally, the use of analytics in the insurance industry has been limited to dashboard reporting in commercial off-the-shelf tools such as Tableau and Microsoft Power BI. These tools, while accessible, lack advanced analytical capabilities for deeper exploratory investigation.\n\nVisual analytics — which integrates data visualisation, statistics, and data mining guided by human judgment — offers a more powerful approach. By combining automated processing with pattern recognition, visual analytics can surface unexpected insights that drive effective data-driven decision-making.\n\n### 1.2 Objective and the Analytical Questions\n\nThis take-home exercise applies appropriate visual analytics techniques to a real-world motor vehicle insurance portfolio from a Spanish non-life insurance company, using **ggplot2** and its extensions in R. The specific analytical questions addressed are:\n\n-   What are the distributions and characteristics of the key numerical and categorical variables in the portfolio?\n\n-   What factors influence the **profitability** (measured by loss ratio) and **volatility** (measured by claim frequency and severity) of the insurance portfolio?\n\n-   Are there statistically significant differences in loss performance across policy types, driver profiles, and geographic segments?\n\n------------------------------------------------------------------------\n\n## 2 Getting Started\n\n### 2.1 Setting the Analytical Tools\n\nThe R packages used in this exercise are:\n\n-   [**tidyverse**](https://www.tidyverse.org/) for data import, wrangling, and visualisation via the grammar of graphics;\n\n-   [**readr**](https://readr.tidyverse.org/) for reading delimited data files;\n\n-   [**ggplot2**](https://ggplot2.tidyverse.org/) as the primary visualisation engine;\n\n-   [**ggdist**](https://mjskay.github.io/ggdist/) for visualising distributions and uncertainty with half-eye and raincloud plots;\n\n-   [**ggridges**](https://cran.r-project.org/web/packages/ggridges/vignettes/introduction.html) for ridgeline density plots across groups;\n\n-   [**ggpubr**](https://rpkgs.datanovia.com/ggpubr/) for annotating statistical test results directly onto plots;\n\n-   [**ggcorrplot**](https://rpkgs.datanovia.com/ggcorrplot/) for visualising correlation matrices;\n\n-   [**patchwork**](https://patchwork.data-imaginist.com/) for composing multiple ggplot2 panels;\n\n-   [**scales**](https://scales.r-lib.org/) for axis formatting (e.g., percent, comma);\n\n-   [**viridis**](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html) for colour-blind-safe palettes; and\n\n-   [**plotly**](https://plotly.com/r/) *(bonus)* for converting ggplot2 charts to interactive visualisations.\n\nThe code chunk below uses `p_load()` from the **pacman** package to check, install, and load all required packages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  tidyverse, readr,\n  ggdist, ggridges, ggpubr,\n  ggcorrplot, patchwork,\n  scales, viridis, plotly\n)\n```\n:::\n\n\nA consistent ggplot2 theme is set globally to maintain visual coherence across all plots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheme_set(\n  theme_minimal(base_size = 12) +\n    theme(\n      plot.title   = element_text(face = \"bold\", hjust = 0.5, size = 13),\n      plot.subtitle = element_text(hjust = 0.5, colour = \"grey40\", size = 11),\n      axis.title.y = element_text(angle = 360, vjust = 0.5, hjust = 1),\n      legend.position = \"bottom\",\n      panel.grid.minor = element_blank()\n    )\n)\n```\n:::\n\n\n### 2.2 Data Source\n\nThe dataset is a real-world motor vehicle insurance portfolio from a Spanish non-life insurance company, made available via [Mendeley Data](https://data.mendeley.com/datasets/sw4jmdb2sm/1). It covers policy years 2022 to 2024 and contains 354,140 policy records across 47 variables, grouped into four domains:\n\n| Domain | Examples |\n|------------------------------------|------------------------------------|\n| Policy & insured characteristics | `policy_type`, `bonus_score`, `payment_frequency` |\n| Driver & vehicle characteristics | `driver_age`, `vehicle_age`, `fuel_type`, `vehicle_brand` |\n| Premiums | `total_premium`, `liability_premium`, coverage-specific premiums |\n| Exposure, claims & incurred costs | `total_claims`, `total_incurred`, `total_exposure` |\n\n------------------------------------------------------------------------\n\n## 3 Data Wrangling\n\n### 3.1 Importing the Data\n\nThe dataset uses a semicolon (`;`) as its delimiter. The `read_delim()` function from **readr** is used to import it correctly, specifying the separator explicitly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- read_delim(\n  \"data/Dataset_of_motor_insurance_portfolio.csv\",\n  delim = \";\",\n  show_col_types = FALSE\n)\n```\n:::\n\n\nA quick inspection confirms the dimensions and column types:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(insurance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 47\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <dbl> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <chr> \"COMP_E\", \"COMP_E\", \"COMP_E\", \"COMP_E\", \"C…\n$ policy_status               <chr> \"C\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A…\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <chr> \"G\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D…\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Rows:\", nrow(insurance), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354140 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Columns:\", ncol(insurance), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nColumns: 47 \n```\n\n\n:::\n:::\n\n\n### 3.2 Checking for Duplicates and Missing Values\n\nAlthough this is a structured administrative dataset, due diligence checks are performed for duplicates and missing values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance[duplicated(insurance), ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 47\n# ℹ 47 variables: insured_id <dbl>, year <dbl>, policy_type <chr>,\n#   policy_status <chr>, business_type <chr>, payment_frequency <chr>,\n#   bonus_score <chr>, driver_age <dbl>, vehicle_age <dbl>,\n#   age_driving_licence <dbl>, fuel_type <chr>, vehicle_value <dbl>,\n#   seats <dbl>, power_to_weight_ratio <dbl>, vehicle_brand <chr>,\n#   municipality_type <chr>, circulation_area <chr>, total_premium <dbl>,\n#   liability_premium <dbl>, property_damage_premium <dbl>, …\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_summary <- colSums(is.na(insurance))\nmissing_summary[missing_summary > 0]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        vehicle_age age_driving_licence           fuel_type       vehicle_value \n                  2                   2                1287                 513 \n```\n\n\n:::\n:::\n\n\nFour variables contain missing values: `vehicle_age` (2 NAs), `age_driving_licence` (2 NAs), `fuel_type` (1,287 NAs), and `vehicle_value` (513 NAs). As `fuel_type` is used in bivariate analysis, missing rows for that variable are excluded in the relevant plots. For numerical variables, missing values are minimal and treated as not available (NA) without imputation, as they represent less than 0.5% of the dataset.\n\n### 3.3 Recoding Categorical Variables\n\nThe categorical variables use abbreviated codes. These are recoded to descriptive labels for readability in charts and interpretations. Ordered factors are used where the variable has a natural order (e.g., `bonus_score`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance |>\n  mutate(\n    policy_type = factor(policy_type,\n      levels = c(\"TP\", \"TPG\", \"CC\", \"COMP_E\", \"COMP_N\"),\n      labels = c(\"Third-Party\", \"TP + Glass\", \"Combined Cover\",\n                 \"Comprehensive (Excess)\", \"Comprehensive (No Excess)\")),\n    policy_status = factor(policy_status,\n      levels = c(\"A\", \"C\"), labels = c(\"Active\", \"Cancelled\")),\n    business_type = factor(business_type,\n      levels = c(\"NB\", \"P\"), labels = c(\"New Business\", \"Portfolio\")),\n    payment_frequency = factor(payment_frequency,\n      levels = c(\"A\", \"S\", \"Q\"), labels = c(\"Annual\", \"Semi-annual\", \"Quarterly\")),\n    bonus_score = factor(bonus_score,\n      levels = c(\"G\", \"N\", \"B\"), labels = c(\"Good\", \"Neutral\", \"Bad\"),\n      ordered = TRUE),\n    fuel_type = factor(fuel_type,\n      levels = c(\"D\", \"G\"), labels = c(\"Diesel\", \"Gasoline\")),\n    municipality_type = factor(municipality_type,\n      levels = c(\"I\", \"C\", \"IS\"), labels = c(\"Inland\", \"Coastal\", \"Islands\")),\n    circulation_area = factor(circulation_area,\n      levels = c(\"U\", \"R\"), labels = c(\"Urban\", \"Rural\"))\n  )\n```\n:::\n\n\n### 3.4 Deriving Actuarial KPI Variables\n\nThe raw dataset contains premiums, claims counts, incurred costs, and exposure, but not the standard actuarial KPIs needed to assess profitability and volatility. These are derived as follows:\n\n| KPI | Formula | Interpretation |\n|---------------------|-------------------------------|----------------------|\n| `loss_ratio` | `total_incurred / total_premium` | Profitability: values \\> 1 indicate underwriting losses |\n| `claim_frequency` | `total_claims / total_exposure` | Volatility: claims per policy year |\n| `claim_severity` | `total_incurred / total_claims` (claims \\> 0) | Average cost per claim |\n| `pure_premium` | `total_incurred / total_exposure` | Risk cost per policy year |\n| `years_licensed` | `year - age_driving_licence` | Driving experience proxy |\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance <- insurance |>\n  mutate(\n    loss_ratio      = total_incurred / total_premium,\n    claim_frequency = total_claims / total_exposure,\n    claim_severity  = if_else(total_claims > 0,\n                              total_incurred / total_claims,\n                              NA_real_),\n    pure_premium    = total_incurred / total_exposure,\n    years_licensed  = year - age_driving_licence\n  )\n```\n:::\n\n\nExtreme outliers in `loss_ratio` (driven by policies with near-zero premiums) are capped at the 99th percentile for visualisation purposes, without modifying the underlying data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlr_cap <- quantile(insurance$loss_ratio, 0.99, na.rm = TRUE)\n\ninsurance_viz <- insurance |>\n  mutate(loss_ratio_capped = pmin(loss_ratio, lr_cap))\n```\n:::\n\n\n### 3.5 Creating Driver Age Bands\n\nDriver age is binned into actuarially meaningful bands that reflect typical risk segmentation in motor insurance underwriting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_viz <- insurance_viz |>\n  mutate(\n    driver_age_band = cut(driver_age,\n      breaks = c(17, 25, 35, 45, 55, 65, Inf),\n      labels = c(\"18–25\", \"26–35\", \"36–45\", \"46–55\", \"56–65\", \"65+\"),\n      right  = TRUE,\n      include.lowest = TRUE)\n  )\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## 4 Exploratory Data Analysis\n\n### 4.1 Univariate Analysis: Numerical Variables\n\n#### 4.1.1 Distribution of Total Premium\n\nThe `total_premium` variable is right-skewed, which is typical for insurance pricing data. A histogram with a density overlay is used to reveal the shape of the distribution, while a log scale highlights the spread across orders of magnitude.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(insurance_viz, aes(x = total_premium)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 60, fill = \"#4B8BBE\", colour = \"white\", linewidth = 0.2) +\n  geom_density(colour = \"#E07B39\", linewidth = 1) +\n  labs(title = \"Distribution of Total Premium\",\n       subtitle = \"Linear scale\",\n       x = \"Total Premium (€)\", y = \"Density\") +\n  scale_x_continuous(labels = comma)\n\np2 <- ggplot(insurance_viz, aes(x = total_premium)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 60, fill = \"#4B8BBE\", colour = \"white\", linewidth = 0.2) +\n  geom_density(colour = \"#E07B39\", linewidth = 1) +\n  scale_x_log10(labels = comma) +\n  labs(title = \"Distribution of Total Premium\",\n       subtitle = \"Log scale\",\n       x = \"Total Premium (€, log scale)\", y = \"Density\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![Distribution of total premium is right-skewed; most policies cluster in the lower premium band.](Take-home_Ex01_files/figure-html/fig-premium-dist-1.png){#fig-premium-dist width=960}\n:::\n:::\n\n\n**Observation**: The distribution is heavily right-skewed on the linear scale. On the log scale, a near-normal distribution emerges, confirming a log-normal data-generating process — consistent with actuarial theory on premium distributions.\n\n#### 4.1.2 Distribution of Driver Age\n\nDriver age is a key risk factor in motor insurance. A histogram with a kernel density curve reveals the age profile of the insured portfolio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(insurance_viz, aes(x = driver_age)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 binwidth = 2, fill = \"#5C9E6E\", colour = \"white\", linewidth = 0.2) +\n  geom_density(colour = \"#C0392B\", linewidth = 1) +\n  labs(title = \"Distribution of Driver Age\",\n       subtitle = \"Portfolio is concentrated in the 35–60 age band\",\n       x = \"Driver Age (years)\", y = \"Density\")\n```\n\n::: {.cell-output-display}\n![Driver age distribution peaks in the 40–55 range, with thin tails at young and older ages.](Take-home_Ex01_files/figure-html/fig-driver-age-dist-1.png){#fig-driver-age-dist width=672}\n:::\n:::\n\n\n**Observation**: The portfolio skews toward middle-aged drivers (35–60 years), with a sharp drop-off for drivers under 25. This likely reflects the higher premiums charged to young drivers, which may discourage uptake.\n\n#### 4.1.3 Distribution of Vehicle Age\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(insurance_viz |> filter(!is.na(vehicle_age)), aes(x = vehicle_age)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 binwidth = 1, fill = \"#8E6ABF\", colour = \"white\", linewidth = 0.2) +\n  geom_density(colour = \"#E07B39\", linewidth = 1) +\n  labs(title = \"Distribution of Vehicle Age\",\n       subtitle = \"Most insured vehicles are between 5 and 20 years old\",\n       x = \"Vehicle Age (years)\", y = \"Density\")\n```\n\n::: {.cell-output-display}\n![Vehicle age is positively skewed, with most insured vehicles under 20 years old.](Take-home_Ex01_files/figure-html/fig-vehicle-age-dist-1.png){#fig-vehicle-age-dist width=672}\n:::\n:::\n\n\n**Observation**: Vehicle age peaks between 5 and 15 years. Very old vehicles (\\>25 years) are rarely insured under comprehensive cover, as their declared value (`vehicle_value`) often does not justify the premium.\n\n#### 4.1.4 Zero-Inflated Distribution of Total Claims\n\nClaim counts are zero-inflated: the vast majority of policies record zero claims in any given year. A lollipop chart is used to communicate this clearly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclaims_count <- insurance_viz |>\n  count(total_claims) |>\n  filter(total_claims <= 6)\n\nggplot(claims_count, aes(x = factor(total_claims), y = n)) +\n  geom_segment(aes(xend = factor(total_claims), yend = 0),\n               colour = \"#4B8BBE\", linewidth = 1) +\n  geom_point(size = 4, colour = \"#4B8BBE\") +\n  scale_y_continuous(labels = comma) +\n  labs(title = \"Frequency of Total Claims per Policy\",\n       subtitle = \"The portfolio is strongly zero-inflated\",\n       x = \"Number of Claims\", y = \"Number of Policies\")\n```\n\n::: {.cell-output-display}\n![Total claims are overwhelmingly zero; a lollipop chart conveys the zero-inflation clearly.](Take-home_Ex01_files/figure-html/fig-claims-dist-1.png){#fig-claims-dist width=672}\n:::\n:::\n\n\n**Observation**: Approximately 80% of policies record zero claims. The zero-inflated nature of the data is critical to understand when modelling claim frequency and should inform the choice of modelling distributions (e.g., zero-inflated Poisson or negative binomial).\n\n---\n\n### 4.2 Univariate Analysis: Categorical Variables\n\n#### 4.2.1 Portfolio Composition by Policy Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_viz |>\n  count(policy_type, sort = TRUE) |>\n  mutate(policy_type = fct_reorder(policy_type, n)) |>\n  ggplot(aes(x = n, y = policy_type, fill = policy_type)) +\n  geom_col(show.legend = FALSE, width = 0.7) +\n  scale_x_continuous(labels = comma) +\n  scale_fill_viridis_d(option = \"D\", direction = -1) +\n  labs(title = \"Portfolio Composition by Policy Type\",\n       subtitle = \"Policy count, all years combined\",\n       x = \"Number of Policies\", y = \"Policy\\nType\")\n```\n\n::: {.cell-output-display}\n![Comprehensive policies dominate the portfolio, with basic third-party cover representing a minority.](Take-home_Ex01_files/figure-html/fig-policy-type-1.png){#fig-policy-type width=768}\n:::\n:::\n\n\n**Observation**: Comprehensive policies with excess (COMP_E) and combined cover (CC) together account for the majority of the portfolio. Basic third-party (TP) policies are the least common, consistent with minimum legal coverage typically held by lower-value vehicle owners.\n\n#### 4.2.2 Distribution of Bonus Score\n\nThe `bonus_score` variable captures the policyholder's claims history — a fundamental risk classification variable in European motor insurance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_viz |>\n  count(bonus_score) |>\n  mutate(pct = n / sum(n)) |>\n  ggplot(aes(x = bonus_score, y = pct, fill = bonus_score)) +\n  geom_col(show.legend = FALSE, width = 0.6) +\n  geom_text(aes(label = percent(pct, accuracy = 0.1)),\n            vjust = -0.5, size = 3.5, fontface = \"bold\") +\n  scale_y_continuous(labels = percent_format()) +\n  scale_fill_manual(values = c(\"Good\" = \"#5C9E6E\", \"Neutral\" = \"#F0C27F\", \"Bad\" = \"#C0392B\")) +\n  labs(title = \"Distribution of Bonus Score\",\n       subtitle = \"Proportion of policies by claims history classification\",\n       x = \"Bonus Score\", y = \"Proportion\")\n```\n\n::: {.cell-output-display}\n![Good bonus scores dominate, indicating a mostly low-risk portfolio.](Take-home_Ex01_files/figure-html/fig-bonus-score-1.png){#fig-bonus-score width=672}\n:::\n:::\n\n\n**Observation**: Over 60% of policyholders carry a \"Good\" bonus score, reflecting a favourable claims history. The relatively small proportion with a \"Bad\" score presents an opportunity to investigate whether this segment drives a disproportionate share of total incurred losses.\n\n#### 4.2.3 Portfolio Split by Geography and Circulation Area\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng1 <- insurance_viz |>\n  count(municipality_type) |>\n  mutate(municipality_type = fct_reorder(municipality_type, n)) |>\n  ggplot(aes(x = n, y = municipality_type, fill = municipality_type)) +\n  geom_col(show.legend = FALSE, width = 0.6) +\n  scale_x_continuous(labels = comma) +\n  scale_fill_viridis_d(option = \"C\") +\n  labs(title = \"By Municipality Type\",\n       x = \"Policy Count\", y = \"Municipality\\nType\")\n\ng2 <- insurance_viz |>\n  count(circulation_area) |>\n  mutate(pct = n / sum(n)) |>\n  ggplot(aes(x = circulation_area, y = pct, fill = circulation_area)) +\n  geom_col(show.legend = FALSE, width = 0.5) +\n  geom_text(aes(label = percent(pct, accuracy = 0.1)),\n            vjust = -0.5, size = 3.5, fontface = \"bold\") +\n  scale_y_continuous(labels = percent_format()) +\n  scale_fill_manual(values = c(\"Urban\" = \"#4B8BBE\", \"Rural\" = \"#8E6ABF\")) +\n  labs(title = \"By Circulation Area\",\n       x = \"Circulation Area\", y = \"Proportion\")\n\ng1 + g2 +\n  plot_annotation(title = \"Geographic Distribution of the Portfolio\",\n                  theme = theme(plot.title = element_text(face = \"bold\", hjust = 0.5)))\n```\n\n::: {.cell-output-display}\n![The portfolio is dominated by inland urban policies, with island-based policies being a small minority.](Take-home_Ex01_files/figure-html/fig-geo-1.png){#fig-geo width=864}\n:::\n:::\n\n\n**Observation**: Inland municipalities account for the largest share of the portfolio. Urban vehicles outnumber rural by a ratio of approximately 3:1, which is important context for interpreting claim frequency differences — urban environments are associated with higher accident frequency.\n\n---\n\n### 4.3 Bivariate Analysis: Profitability Drivers\n\n#### 4.3.1 Loss Ratio by Policy Type\n\nA violin plot combined with a boxplot reveals both the distribution shape and key summary statistics of the loss ratio across policy types. Statistical significance is assessed using a Kruskal-Wallis test with pairwise comparisons annotated directly on the chart.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(insurance_viz |> filter(loss_ratio_capped > 0, total_exposure > 0),\n       aes(x = policy_type, y = loss_ratio_capped, fill = policy_type)) +\n  geom_violin(alpha = 0.4, trim = TRUE, show.legend = FALSE) +\n  geom_boxplot(width = 0.15, outlier.shape = NA, show.legend = FALSE,\n               fill = \"white\", colour = \"grey40\") +\n  stat_compare_means(method = \"kruskal.test\",\n                     label.x = 1.2, label.y = max(insurance_viz$loss_ratio_capped, na.rm = TRUE) * 0.95) +\n  scale_fill_viridis_d(option = \"D\") +\n  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +\n  labs(title = \"Loss Ratio by Policy Type\",\n       subtitle = \"Kruskal-Wallis test for group differences; policies with zero claims excluded\",\n       x = \"Policy Type\", y = \"Loss\\nRatio\")\n```\n\n::: {.cell-output-display}\n![Loss ratio varies significantly across policy types; comprehensive cover shows greater volatility.](Take-home_Ex01_files/figure-html/fig-lr-policy-type-1.png){#fig-lr-policy-type width=960}\n:::\n:::\n\n\n**Observation**: Comprehensive cover policies (particularly those without excess) exhibit higher median loss ratios and wider distributions, reflecting greater exposure to claim frequency and larger claim amounts. The Kruskal-Wallis test confirms statistically significant differences in loss ratio across policy types (p < 0.05).\n\n#### 4.3.2 Loss Ratio by Bonus Score\n\nBonus score is a direct actuarial signal of policyholder risk. Its relationship with loss ratio should be monotonic if the scoring system is predictive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(insurance_viz |> filter(loss_ratio_capped > 0),\n       aes(x = bonus_score, y = loss_ratio_capped, fill = bonus_score)) +\n  stat_halfeye(adjust = 0.5, justification = -0.2, .width = 0,\n               point_colour = NA, alpha = 0.6) +\n  geom_boxplot(width = 0.15, outlier.shape = NA, fill = \"white\", colour = \"grey40\") +\n  stat_compare_means(comparisons = list(c(\"Good\", \"Bad\"), c(\"Good\", \"Neutral\"), c(\"Neutral\", \"Bad\")),\n                     method = \"wilcox.test\", label = \"p.signif\") +\n  scale_fill_manual(values = c(\"Good\" = \"#5C9E6E\", \"Neutral\" = \"#F0C27F\", \"Bad\" = \"#C0392B\")) +\n  labs(title = \"Loss Ratio by Bonus Score\",\n       subtitle = \"Half-eye + boxplot; pairwise Wilcoxon tests annotated\",\n       x = \"Bonus Score\", y = \"Loss\\nRatio\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Policyholders with a Bad bonus score show materially higher and more volatile loss ratios.](Take-home_Ex01_files/figure-html/fig-lr-bonus-1.png){#fig-lr-bonus width=768}\n:::\n:::\n\n\n**Observation**: The loss ratio increases monotonically from Good to Bad bonus score, validating the bonus system's actuarial predictiveness. Policyholders with a \"Bad\" score not only have higher median loss ratios but also a heavier right tail, indicating they are associated with disproportionately large individual losses.\n\n#### 4.3.3 Loss Ratio by Circulation Area and Municipality\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlr_geo <- insurance_viz |>\n  filter(loss_ratio_capped > 0, total_exposure > 0) |>\n  group_by(municipality_type, circulation_area) |>\n  summarise(median_lr = median(loss_ratio_capped, na.rm = TRUE),\n            mean_lr   = mean(loss_ratio_capped, na.rm = TRUE),\n            n         = n(),\n            .groups   = \"drop\")\n\nggplot(lr_geo, aes(x = municipality_type, y = median_lr, fill = circulation_area)) +\n  geom_col(position = position_dodge(width = 0.7), width = 0.6) +\n  geom_text(aes(label = round(median_lr, 2)),\n            position = position_dodge(width = 0.7), vjust = -0.5, size = 3.5) +\n  scale_fill_manual(values = c(\"Urban\" = \"#4B8BBE\", \"Rural\" = \"#8E6ABF\"),\n                    name = \"Circulation Area\") +\n  labs(title = \"Median Loss Ratio by Municipality Type and Circulation Area\",\n       subtitle = \"Urban and island policies exhibit higher loss ratios\",\n       x = \"Municipality Type\", y = \"Median Loss\\nRatio\")\n```\n\n::: {.cell-output-display}\n![Urban policies show higher loss ratios than rural; island policies present the highest median loss.](Take-home_Ex01_files/figure-html/fig-lr-geo-1.png){#fig-lr-geo width=960}\n:::\n:::\n\n\n**Observation**: Urban policies record higher median loss ratios than rural equivalents across all municipality types, consistent with higher accident frequency in congested urban environments. Island policies, despite low policy volumes, exhibit elevated loss ratios — potentially driven by limited repair infrastructure and higher severity per claim.\n\n---\n\n### 4.4 Bivariate Analysis: Volatility Drivers\n\n#### 4.4.1 Claim Frequency by Driver Age Band\n\nA GAM smoother (generalised additive model) is overlaid on a scatter plot of claim frequency against driver age to reveal non-linear risk patterns that linear regression would miss.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_viz |>\n  filter(total_exposure > 0, claim_frequency < 10) |>\n  ggplot(aes(x = driver_age, y = claim_frequency)) +\n  geom_hex(bins = 50, aes(fill = after_stat(log(count))), show.legend = TRUE) +\n  geom_smooth(method = \"gam\", formula = y ~ s(x, bs = \"cs\"),\n              colour = \"#C0392B\", linewidth = 1.2, se = TRUE) +\n  scale_fill_viridis_c(name = \"log(count)\", option = \"magma\") +\n  labs(title = \"Claim Frequency vs Driver Age\",\n       subtitle = \"GAM smooth with 95% CI; hex density shows data concentration\",\n       x = \"Driver Age (years)\", y = \"Claim\\nFrequency\")\n```\n\n::: {.cell-output-display}\n![Claim frequency follows a U-shaped curve with driver age, highest for youngest and oldest drivers.](Take-home_Ex01_files/figure-html/fig-freq-age-1.png){#fig-freq-age width=864}\n:::\n:::\n\n\n**Observation**: The GAM smoother reveals a U-shaped relationship: young drivers (under 25) and older drivers (over 65) exhibit higher claim frequencies. The 35–55 age band represents the lowest-risk segment — a finding consistent with actuarial pricing conventions across European motor insurance markets.\n\n#### 4.4.2 Claim Frequency by Vehicle Age Band\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_viz |>\n  filter(!is.na(vehicle_age), total_exposure > 0, claim_frequency < 10) |>\n  ggplot(aes(x = vehicle_age, y = claim_frequency)) +\n  geom_point(alpha = 0.05, colour = \"#4B8BBE\") +\n  geom_smooth(method = \"gam\", formula = y ~ s(x, bs = \"cs\"),\n              colour = \"#E07B39\", linewidth = 1.2, se = TRUE) +\n  labs(title = \"Claim Frequency vs Vehicle Age\",\n       subtitle = \"GAM smooth with 95% CI\",\n       x = \"Vehicle Age (years)\", y = \"Claim\\nFrequency\")\n```\n\n::: {.cell-output-display}\n![Newer vehicles tend to record lower claim frequency, though very old vehicles also show reduced frequency.](Take-home_Ex01_files/figure-html/fig-freq-vehicle-age-1.png){#fig-freq-vehicle-age width=864}\n:::\n:::\n\n\n**Observation**: Newer vehicles (under 5 years) tend to have lower claim frequencies, likely reflecting the higher proportion of experienced drivers who purchase new vehicles. A slight increase is observed for vehicles aged 10–20 years, potentially reflecting higher mechanical vulnerability and older associated driver profiles.\n\n#### 4.4.3 Claim Severity by Fuel Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_viz |>\n  filter(!is.na(claim_severity), !is.na(fuel_type)) |>\n  ggplot(aes(x = fuel_type, y = claim_severity, fill = fuel_type)) +\n  stat_halfeye(adjust = 0.5, justification = -0.2, .width = 0,\n               point_colour = NA, alpha = 0.6) +\n  geom_boxplot(width = 0.15, outlier.shape = NA, fill = \"white\", colour = \"grey40\") +\n  stat_compare_means(method = \"wilcox.test\", label = \"p.format\",\n                     label.x = 1.5, label.y.npc = 0.9) +\n  scale_fill_manual(values = c(\"Diesel\" = \"#4B8BBE\", \"Gasoline\" = \"#E07B39\")) +\n  scale_y_log10(labels = comma) +\n  labs(title = \"Claim Severity by Fuel Type\",\n       subtitle = \"Log-scaled y-axis; Wilcoxon test for group difference\",\n       x = \"Fuel Type\", y = \"Claim\\nSeverity (€, log)\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Diesel vehicles exhibit higher claim severity than gasoline vehicles on average.](Take-home_Ex01_files/figure-html/fig-severity-fuel-1.png){#fig-severity-fuel width=768}\n:::\n:::\n\n\n**Observation**: Diesel vehicles exhibit statistically higher claim severity than gasoline vehicles (Wilcoxon p < 0.05). This may reflect the higher vehicle values and greater cost of parts for diesel models, which tend to be larger family cars and commercial vehicles.\n\n---\n\n### 4.5 Temporal Analysis: 2022–2024 Trends\n\n#### 4.5.1 Portfolio Growth and Premium Trends\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrend_data <- insurance_viz |>\n  group_by(year) |>\n  summarise(\n    policy_count  = n(),\n    avg_premium   = mean(total_premium, na.rm = TRUE),\n    avg_loss_ratio = mean(loss_ratio_capped, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\nt1 <- ggplot(trend_data, aes(x = year, y = policy_count)) +\n  geom_line(colour = \"#4B8BBE\", linewidth = 1.2) +\n  geom_point(size = 3, colour = \"#4B8BBE\") +\n  scale_y_continuous(labels = comma) +\n  labs(title = \"Policy Count by Year\", x = \"Year\", y = \"Policy\\nCount\")\n\nt2 <- ggplot(trend_data, aes(x = year, y = avg_premium)) +\n  geom_line(colour = \"#5C9E6E\", linewidth = 1.2) +\n  geom_point(size = 3, colour = \"#5C9E6E\") +\n  scale_y_continuous(labels = comma) +\n  labs(title = \"Average Premium by Year\", x = \"Year\", y = \"Avg Premium\\n(€)\")\n\nt3 <- ggplot(trend_data, aes(x = year, y = avg_loss_ratio)) +\n  geom_line(colour = \"#C0392B\", linewidth = 1.2) +\n  geom_point(size = 3, colour = \"#C0392B\") +\n  geom_hline(yintercept = 1, linetype = \"dashed\", colour = \"grey50\") +\n  labs(title = \"Average Loss Ratio by Year\",\n       subtitle = \"Dashed line = break-even\",\n       x = \"Year\", y = \"Avg Loss\\nRatio\")\n\nt1 + t2 + t3\n```\n\n::: {.cell-output-display}\n![Policy count and average premium both grew over 2022–2024, indicating portfolio expansion.](Take-home_Ex01_files/figure-html/fig-temporal-1.png){#fig-temporal width=960}\n:::\n:::\n\n\n**Observation**: Policy count and average premium increased year-on-year over 2022–2024, suggesting portfolio growth. The average loss ratio dipped below 1 in the most recent year, indicating improving aggregate profitability — though significant cross-segment variation persists as shown in previous sections.\n\n#### 4.5.2 Year-over-Year Loss Ratio by Policy Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_viz |>\n  filter(total_exposure > 0, total_premium > 0) |>\n  group_by(year, policy_type) |>\n  summarise(median_lr = median(loss_ratio_capped, na.rm = TRUE), .groups = \"drop\") |>\n  ggplot(aes(x = year, y = median_lr, colour = policy_type, group = policy_type)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2.5) +\n  facet_wrap(~policy_type, nrow = 1, scales = \"free_y\") +\n  scale_colour_viridis_d(option = \"D\") +\n  labs(title = \"Median Loss Ratio by Year and Policy Type\",\n       subtitle = \"Faceted to reveal segment-level trends independently\",\n       x = \"Year\", y = \"Median\\nLoss Ratio\") +\n  theme(legend.position = \"none\",\n        strip.text = element_text(size = 9))\n```\n\n::: {.cell-output-display}\n![Loss ratio trends vary markedly by policy type; comprehensive cover shows the most volatility.](Take-home_Ex01_files/figure-html/fig-lr-temporal-facet-1.png){#fig-lr-temporal-facet width=1056}\n:::\n:::\n\n\n**Observation**: Loss ratio trends diverge meaningfully by policy type over the three-year window. Comprehensive cover without excess (COMP_N) exhibits the highest volatility year-on-year, while basic third-party (TP) remains the most stable. This has implications for reserving and pricing review cycles.\n\n---\n\n### 4.6 Bonus: Correlation Heatmap of Premium and Incurred Variables\n\nBeyond the analytical methods taught in class, a correlation heatmap is used to examine the multivariate structure of premium and incurred cost variables simultaneously. This visual analytics technique identifies co-dependency between coverage lines that would be invisible in pairwise bivariate analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorr_vars <- insurance_viz |>\n  select(total_premium, liability_premium, property_damage_premium,\n         theft_premium, fire_premium, glass_premium,\n         total_incurred, liability_incurred, property_incurred,\n         theft_incurred, fire_incurred, glass_incurred) |>\n  drop_na()\n\ncorr_matrix <- cor(corr_vars, method = \"spearman\")\n\nggcorrplot(corr_matrix,\n           method  = \"square\",\n           type    = \"lower\",\n           lab     = TRUE,\n           lab_size = 2.8,\n           colors  = c(\"#C0392B\", \"white\", \"#2E86C1\"),\n           title   = \"Spearman Correlation: Premium and Incurred Variables\",\n           ggtheme = theme_minimal(base_size = 11)) +\n  theme(plot.title = element_text(face = \"bold\", hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![Strong correlations between premium components reflect the bundled nature of comprehensive cover.](Take-home_Ex01_files/figure-html/fig-corr-heatmap-1.png){#fig-corr-heatmap width=864}\n:::\n:::\n\n\n**Observation**: Premium components are highly correlated with one another — a natural consequence of comprehensive policies bundling multiple coverages, so that a policy with high total premium will also have high sub-premiums across lines. On the incurred side, correlations are lower and more variable, reflecting the independence of individual claim events across coverage lines. The low correlation between incurred and premium variables highlights that premium adequacy varies across coverage types.\n\n---\n\n### 4.7 Bonus: Interactive Loss Ratio Explorer\n\nThe ggplot2 chart from Section 4.3.1 is converted to an interactive plotly visualisation, enabling hover inspection of individual data points — a capability that static charts cannot provide.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_static <- ggplot(\n  insurance_viz |>\n    filter(loss_ratio_capped > 0, total_exposure > 0) |>\n    group_by(policy_type, bonus_score) |>\n    summarise(\n      median_lr = median(loss_ratio_capped, na.rm = TRUE),\n      n         = n(),\n      .groups   = \"drop\"\n    ),\n  aes(x = policy_type, y = median_lr, fill = bonus_score,\n      text = paste0(\"Policy Type: \", policy_type,\n                    \"<br>Bonus Score: \", bonus_score,\n                    \"<br>Median LR: \", round(median_lr, 3),\n                    \"<br>N policies: \", comma(n)))\n) +\n  geom_col(position = position_dodge(width = 0.75), width = 0.7) +\n  scale_fill_manual(values = c(\"Good\" = \"#5C9E6E\", \"Neutral\" = \"#F0C27F\", \"Bad\" = \"#C0392B\"),\n                    name = \"Bonus Score\") +\n  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +\n  labs(title = \"Median Loss Ratio by Policy Type and Bonus Score\",\n       x = \"Policy Type\", y = \"Median Loss Ratio\")\n\nggplotly(p_static, tooltip = \"text\")\n```\n\n::: {#fig-interactive-lr .cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-bad20ca8ce5e0f92b15b\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-bad20ca8ce5e0f92b15b\">{\"x\":{\"data\":[{\"orientation\":\"v\",\"width\":[0.23333333333333339,0.23333333333333339,0.23333333333333339,0.23333333333333339,0.2333333333333325],\"base\":[0,0,0,0,0],\"x\":[0.75,1.75,2.75,3.75,4.75],\"y\":[5.0548208530104812,2.8419071754064795,2.7012208230697841,1.9911452792137949,1.9606692173067395],\"text\":[\"Policy Type: Third-Party<br>Bonus Score: Good<br>Median LR: 5.055<br>N policies: 281\",\"Policy Type: TP + Glass<br>Bonus Score: Good<br>Median LR: 2.842<br>N policies: 3,003\",\"Policy Type: Combined Cover<br>Bonus Score: Good<br>Median LR: 2.701<br>N policies: 18,520\",\"Policy Type: Comprehensive (Excess)<br>Bonus Score: Good<br>Median LR: 1.991<br>N policies: 14,079\",\"Policy Type: Comprehensive (No Excess)<br>Bonus Score: Good<br>Median LR: 1.961<br>N policies: 4,298\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(92,158,110,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"transparent\"}},\"name\":\"Good\",\"legendgroup\":\"Good\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.23333333333333339,0.23333333333333339,0.23333333333333339,0.23333333333333295,0.2333333333333325],\"base\":[0,0,0,0,0],\"x\":[1,2,3,4,5],\"y\":[4.9682701216744789,1.723370249171029,2.2618839818492811,1.7688453629922898,1.5394684180397165],\"text\":[\"Policy Type: Third-Party<br>Bonus Score: Neutral<br>Median LR: 4.968<br>N policies: 16\",\"Policy Type: TP + Glass<br>Bonus Score: Neutral<br>Median LR: 1.723<br>N policies: 105\",\"Policy Type: Combined Cover<br>Bonus Score: Neutral<br>Median LR: 2.262<br>N policies: 552\",\"Policy Type: Comprehensive (Excess)<br>Bonus Score: Neutral<br>Median LR: 1.769<br>N policies: 289\",\"Policy Type: Comprehensive (No Excess)<br>Bonus Score: Neutral<br>Median LR: 1.539<br>N policies: 208\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(240,194,127,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"transparent\"}},\"name\":\"Neutral\",\"legendgroup\":\"Neutral\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.23333333333333339,0.23333333333333339,0.23333333333333339,0.2333333333333325,0.2333333333333325],\"base\":[0,0,0,0,0],\"x\":[1.25,2.25,3.25,4.25,5.25],\"y\":[2.3533214139261189,1.9653273531766253,1.7860367963424819,1.6390540112040541,1.2278568415009858],\"text\":[\"Policy Type: Third-Party<br>Bonus Score: Bad<br>Median LR: 2.353<br>N policies: 6\",\"Policy Type: TP + Glass<br>Bonus Score: Bad<br>Median LR: 1.965<br>N policies: 94\",\"Policy Type: Combined Cover<br>Bonus Score: Bad<br>Median LR: 1.786<br>N policies: 374\",\"Policy Type: Comprehensive (Excess)<br>Bonus Score: Bad<br>Median LR: 1.639<br>N policies: 234\",\"Policy Type: Comprehensive (No Excess)<br>Bonus Score: Bad<br>Median LR: 1.228<br>N policies: 204\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(192,57,43,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"transparent\"}},\"name\":\"Bad\",\"legendgroup\":\"Bad\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":41.238688252386879,\"r\":7.9701120797011216,\"b\":40.647571606475722,\"l\":153.82316313823165},\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243},\"title\":{\"text\":\"<b> Median Loss Ratio by Policy Type and Bonus Score <\\/b>\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.268576172685762},\"x\":0.5,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,5.5999999999999996],\"tickmode\":\"array\",\"ticktext\":[\"Third-Party\",\"TP + Glass\",\"Combined<br />Cover\",\"Comprehensive<br />(Excess)\",\"Comprehensive<br />(No<br />Excess)\"],\"tickvals\":[1,2,3,4,5],\"categoryorder\":\"array\",\"categoryarray\":[\"Third-Party\",\"TP + Glass\",\"Combined<br />Cover\",\"Comprehensive<br />(Excess)\",\"Comprehensive<br />(No<br />Excess)\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Policy Type\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.25274104265052405,5.3075618956610056],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\"],\"tickvals\":[0,1,1.9999999999999998,3,4,5],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Median Loss Ratio\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"shapes\":[],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":12.7521793275218},\"orientation\":\"h\",\"x\":0.5,\"y\":-0.14999999999999999,\"xanchor\":\"center\",\"yanchor\":\"top\",\"title\":{\"text\":\"Bonus Score\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"293066192822\":{\"x\":{},\"y\":{},\"fill\":{},\"text\":{},\"type\":\"bar\"}},\"cur_data\":\"293066192822\",\"visdat\":{\"293066192822\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nInteractive version of loss ratio by policy type; hover for policy-level details.\n:::\n:::\n\n\n**Observation**: The interactive chart confirms the combined effect of policy type and bonus score on loss ratio. Within every policy type, the \"Bad\" bonus score segment consistently records the highest median loss ratio. Hover inspection reveals that the \"Bad\" / Comprehensive (No Excess) combination represents the highest-risk segment in the portfolio, warranting targeted underwriting action.\n\n---\n\n## 5 Conclusion\n\nThis exercise demonstrates the value of visual analytics for insurance portfolio investigation. Through a combination of univariate, bivariate, and temporal techniques implemented in **ggplot2** and its extensions, several key insights emerged:\n\n- The portfolio is dominated by middle-aged drivers on inland urban policies holding comprehensive cover, with predominantly favourable bonus scores.\n- Loss ratio is significantly influenced by **policy type**, **bonus score**, and **geography**, with comprehensive policies, bad bonus scores, and urban/island exposure representing the highest-risk segments.\n- **Claim frequency** follows a U-shaped curve with driver age, confirming the actuarial basis for age-based risk pricing. **Claim severity** is higher for diesel vehicles.\n- Premium and incurred components are structurally correlated, but the weak premium-to-incurred correlations suggest pricing inadequacy in specific coverage lines.\n- Temporal analysis reveals year-on-year portfolio growth alongside improving aggregate profitability, though segment-level volatility remains high for comprehensive cover.\n\nThese insights provide a foundation for more targeted underwriting strategy, pricing refinement, and reserving review. Future work could enrich this analysis with external geospatial data and predictive modelling of individual loss ratios.\n\n---\n\n## 6 Key References\n\n-   [R for Visual Analytics](https://r4va.netlify.app/)\n\n-   [R for Data Science (2nd ed.)](https://r4ds.hadley.nz/)\n\n-   [Fundamentals of Data Visualisation](https://clauswilke.com/dataviz/)\n\n-   [ggplot2 Extensions Gallery](https://exts.ggplot2.tidyverse.org/gallery/)\n\n-   Swiss Re Institute. (2019). [Advanced analytics: unlocking new frontiers in P&C insurance](https://www.swissre.com/dam/jcr:3257ef4b-fe20-45e2-9700-7677702407af/sigma4_2019_en.pdf). *sigma No. 4/2019*.\n\n-   Mendeley Data. Motor Vehicle Insurance Portfolio Dataset. <https://data.mendeley.com/datasets/sw4jmdb2sm/1>\n\n**~~~ End of Take-home Exercise 01 ~~~**\n",
    "supporting": [
      "Take-home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.12.0/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}